apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
data:
  db-user: dGFza3VzZXI=
  db-password: dGFza3Bhc3M=
  db-name: dGFza3RyYWNrZXI=
  secret-key: dGFzdC1zZWNyZXQta2V5LWNoYW5nZS1tZS1pbi1wcm9kdWN0aW9u
